/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'welcome',
    {
        type: 'category',
        label: 'KPI Matrix',
        link: {type: 'doc', id: 'kpi-matrix'},
        items: [
                {type: 'doc', id: 'KPIMatrix/kpim-security', label: 'Security'},
                {type: 'doc', id: 'KPIMatrix/kpim-create-edit', label: 'Creeate and Edit Matrix'},
                {type: 'doc', id: 'KPIMatrix/kpim-view', label: 'View Matrix'},
                {type: 'doc', id: 'KPIMatrix/kpim-tag-history', label: 'Tag History'},
                ],
    },
    {
        type: 'category',
        label: 'Dashboard',
        link: {type: 'doc', id: 'dashboard'},
        items: [
                {type: 'doc', id: 'Dashboard/dashboard-viewer', label: 'Dashboard Viewer'},
                {type: 'doc', id: 'Dashboard/dashboard-edit', label: 'Dashboard - Create and Edit'},
                {type: 'doc', id: 'Dashboard/dashboard-preview', label: 'Dashboard Preview'},
                {type: 'doc', id: 'Dashboard/dashboard-roles', label: 'Dashboard Roles'},
                {type: 'doc', id: 'Dashboard/dashboard-marquee', label: 'Dashboard Marquee'},
                ],
    },
  ],
};
module.exports = sidebars;
